common:
  env: dev
  ingress:
    host: getting-started.dev.entur.io
  container:
    env:
      - name: GCP_PROJECT
        value: ent-getstarted-dev
  configmap:
    enabled: true
    toEnv: true
    data:
      ENV: dev
  secrets:
    app-secrets:  # k8s secret name "appname+this" => "getting-started-app-secrets"
      - ROCKET_SECRET  # SM Secret name resulting in k8s-secret key and ENV var name, secrets containing dashes(-) will not be visible in the pod
      # - ROCKET_SECRET2
      # - ROCKET_SECRET3