# TODO: only build and tf plan for PR
options:
  dynamic_substitutions: true  
  logging: CLOUD_LOGGING_ONLY
  env:
    - DOCKER_BUILDKIT=1

substitutions:
  _IMAGE_NAME: getting-started
  # _IMAGE_VERSION: '$BRANCH_NAME.$SHORT_SHA'
  _IMAGE_VERSION: $SHORT_SHA
  _ENV_NAME: sbx
  _ENV: kub-ent-${_ENV_NAME}
  _CLOUDSDK_COMPUTE_ZONE: europe-west1-b
  _CLOUDSDK_CONTAINER_CLUSTER: ${_ENV}-001

  _REGISTRY: europe-west1-docker.pkg.dev
  _REPOSITORY: ${_IMAGE_NAME}
  _IMAGE: ${_REGISTRY}/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}

tags:
  - build
  - ${_IMAGE_NAME}

timeout: 3660s

images:
  # - ${_REGISTRY}/${PROJECT_ID}/${_IMAGE_NAME}
  - ${_REGISTRY}/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}

# availableSecrets:
#   secretManager:
#     - versionName: projects/${PROJECT_ID}/secrets/SECRET_NAME/versions/latest
#       env: 'SECRET_NAME'

steps:
  # TODO: Run unit tests if not part of docker build

  - id: build-getstarted
    name: 'gcr.io/cloud-builders/docker'
  # secretEnv:
  #  - SECRET_NAME
    args:
      - 'build'
      - '--tag=${_IMAGE}:latest'
      - '--tag=${_IMAGE}:${_ENV_NAME}'
      - '--tag=${_IMAGE}:${_IMAGE_VERSION}'
      - --build-arg=BUILDKIT_INLINE_CACHE=1
      - --cache-from=${_IMAGE}:latest
      - --cache-from=${_IMAGE}:${_IMAGE_VERSION}
      - --cache-from=${_IMAGE}:dev
      - --cache-from=${_IMAGE}:tst
      - --cache-from=${_IMAGE}:prd
      - '.'
    timeout: 3600s

  - id: push-getstarted
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}:${_IMAGE_VERSION}']

  # Install helm dependencies, no more `./charts` and `.tgz` archive
  - name: 'eu.gcr.io/entur-system-1287/helm'
    args: 
      - 'dependency'
      - 'update'
      - 'helm/getting-started'

  # Render Helm template
  - name: 'eu.gcr.io/entur-system-1287/helm'
    args: 
      - 'template'
      - '--output-dir'
      - 'chart'
      - '--namespace'
      - 'getting-started'
      - 'getting-started'
      - '--set common.container.image=${_IMAGE}:${_IMAGE_VERSION}'
      - '-f'
      - 'helm/getting-started/env/values-${_ENV}.yaml'
      - 'helm/getting-started'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'

  # Apply terraform changes
  - name: 'hashicorp/terraform:1.1.0'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform init
        terraform validate
        terraform plan --var-file=env/${_ENV}.tfvars -out terraform.plan
        terraform apply --auto-approve terraform.plan

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-k', 'chart']
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'

  # TODO: smoke tests?
  # TODO: sync apigee
  # TODO: publish developer docs