 common:
  app: hest-er-best
  shortname: hest
  team: plattform
  ingress:
    trafficType: public
  container:
    cpu: "0.006"
    memory: 78
    probes:
      liveness:
        path: "/greet"
      readiness:
        path: "/greet"
    prometheus:
      enabled: false
