{{- if or .Values.ingresses .Values.ingress.enabled }}
  {{- /* Rules */}}
  {{- $externalPort :=  .Values.service.externalPort  -}}
  {{- $chart := . -}}
  {{- $releaseName := include "name" . -}}
  {{- $releaseNamespace := .Release.Namespace -}}
  {{- $ingresses := .Values.ingresses | default (list .Values.ingress) -}}

{{- /* YAML Spec */}}
{{ range $ingresses }}
{{- $checkTrafficType := .trafficType | required "ingress.trafficType is required." -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  {{- if .annotations }}
    {{- toYaml .annotations | nindent 4 }}
  {{- end }}
  labels:
    traffic-type: {{.trafficType }}
    {{- include "labels" $chart |trim| nindent 4 }}
  name: {{ .name | default $releaseName }}
  namespace: {{ $releaseNamespace }}
spec:
  rules:
  {{- if .rules -}}
  {{ toYaml .rules | nindent 4 }}
  {{- else }}
  - host: {{ .host | required ".Values.common.ingress.host is required." }}
    http:
      paths:
      - backend:
          service:
            name: {{ $releaseName }}
            port:
              number: {{ $externalPort }}
        pathType: ImplementationSpecific
  {{- end }}

# Must manually print newlines for unittest, do not remove
{{ print "\n---\n" }}

{{- end }}
{{- end }}
