{{- if hasKey .Values "serviceAccount" }}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: application
  labels:
    {{- include "labels" . |trim| nindent 4 }}
{{- end }}
{{- end }}
