name: Continous Deployment

on:
  pull_request:
    branches:
      - master
      - main
    types:
      - closed

jobs:
  tf-plan:
    name: Terraform plan
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        env: [dev, prd]
    uses: entur/tmp-github-actions-2/.github/workflows/tf-apply.yml@master
    with:
      tf_version: 1.1.0
      environment: ${{ matrix.env }}
