name: Continous Deployment

on:
  pull_request:
    branches:
      - master
      - main
    types:
      - closed

jobs:
  tf-apply-dev:
    name: Terraform apply
    uses: entur/tmp-github-actions-2/.github/workflows/tf-apply.yml@master
    with:
      tf_version: 1.1.0
      environment: dev
    secrets: inherit

  tf-apply-prd:
    name: Terraform apply
    uses: entur/tmp-github-actions-2/.github/workflows/tf-apply.yml@master
    with:
      tf_version: 1.1.0
      environment: prd
    secrets: inherit
