name: Continous deployment

on:
  pull_request:
    branches:
      - master
      - main
    types:
      - closed

jobs:
  tf-apply-dev:
    name: Terraform apply dev
    uses: entur/tmp-github-actions-2/.github/workflows/tf-apply.yml@master
    with:
      tf_version: 1.1.0
      environment: dev
    secrets: inherit

  # docker-upload

  helm-deploy-dev:
    name: Deploy app to dev
    uses: entur/tmp-github-actions-2/.github/workflows/helm-deploy.yml@master
    with:
      release_name: hest-er-best
      namespace: hest-er-best
      environment: dev
    needs: [tf-apply-dev]
    secrets: inherit

  tf-apply-prd:
    name: Terraform apply prd
    uses: entur/tmp-github-actions-2/.github/workflows/tf-apply.yml@master
    with:
      tf_version: 1.1.0
      environment: prd
    secrets: inherit
    needs: [helm-deploy-dev]

  helm-deploy-prd:
    name: Deploy app to prd
    uses: entur/tmp-github-actions-2/.github/workflows/helm-deploy.yml@master
    with:
      release_name: hest-er-best
      namespace: hest-er-best
      environment: prd
    needs: [tf-apply-prd]
    secrets: inherit
