name: Continous Integration 2

on:
  pull_request:
    branches:
      - master
      - main
    types:
      - opened
      - synchronize
      - edited

jobs:
  tf-plan:
    name: Terraform plan
    secrets: inherit
    strategy:
      matrix:
        env: [dev, prd]
    uses: entur/tmp-github-actions-2/.github/workflows/tf-plan.yml@master
    with:
      tf_version: 1.1.0
      environment: ${{ matrix.env }}
