name: Continous Integration

on:
  pull_request:
    branches:
      - master
      - main
    types:
      - opened
      - synchronize
      - edited

env:
  TERRAFORM_VERSION: 1.1.0

jobs:
  tf-plan:
    uses: entur/tmp-github-actions-2/.github/workflows/tf-plan.yml@master
  golden-ci:
    uses: entur/tmp-github-actions-2/.github/workflows/golden-ci-rust.yml@master
    # secrets:
    #   token: ${{ secrets.GITHUB_TOKEN }}
