name: Continous Integration

on:
  pull_request:
    branches:
      - master
      - main
    types:
      - opened
      - synchronize
      - edited

jobs:
  golden-ci:
    uses: entur/tmp-github-actions-2/workflows/golden-ci-rust.yml@master
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
