name: Continous Integration

on:
  pull_request:
    branches:
      - master
      - main
    types:
      - opened
      - synchronize
      - edited

jobs:
  tf-plan:
    name: Terraform plan
    strategy:
      fail-fast: false
      matrix:
        env: [dev, prd]
    uses: entur/tmp-github-actions-2/.github/workflows/tf-plan.yml@master
    with:
      tf_version: 1.1.0
      environment: ${{ matrix.env }}
    secrets: inherit

  ci-app:
    uses: entur/tmp-github-actions-2/.github/workflows/ci-gradle.yml@master
    # with:
    #   java_version: '17'
    #   java_distribution: 'temurin'
    # secrets:
    #   token: ${{ secrets.GITHUB_TOKEN }}
