name: Continous integration

on:
  pull_request:
    branches:
      - master
      - main
    types:
      - opened
      - synchronize
      - edited

jobs:
  # tf-plan:
  #   name: Terraform plan
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       env: [dev, prd]
  #   uses: entur/tmp-github-actions-2/.github/workflows/tf-plan.yml@master
  #   with:
  #     tf_version: 1.1.0
  #     environment: ${{ matrix.env }}
  #   secrets: inherit

  # ci-gradle:
  #   name: CI Gradle
  #   uses: entur/tmp-github-actions-2/.github/workflows/ci-gradle.yml@master
  #   with:
  #     app_name: ci-cd-demo
  #     java_version: '20'

  # ci-insights:
  #   name: CI insights
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       env: [dev, prd]
  #   uses: entur/tmp-github-actions-2/.github/workflows/ci-insight.yml@master
  #   with:
  #     environment: ${{ matrix.env }}
  #   secrets: inherit

  # ci-docker:
  #   name: CI Docker
  #   uses: entur/tmp-github-actions-2/.github/workflows/ci-docker.yml@master
  #   if: needs.ci-gradle.outputs.built-app
  #   needs: [ci-gradle]

  cd-docker:
    name: CD Docker
    uses: entur/tmp-github-actions-2/.github/workflows/cd-docker.yml@master
    with:
      app_name: ci-cd-demo
      download_artifact: false
    # needs: [ci-docker]
    secrets: inherit

