name: Continous integration

on:
  pull_request:
    branches:
      - master
      - main
    types:
      - opened
      - synchronize
      - edited

jobs:
  test-cd-output:
    name: Test CD output
    uses: entur/tmp-github-actions-2/.github/workflows/cd-docker.yml@master
    with:
      app_name: hest-er-best
    secrets: inherit
  test-cd-output-print:
    name: Test CD output print
    needs: test-cd-output
    runs-on: ubuntu-latest
    steps:
      - id: echo
        run: echo ${{ needs.test-cd-output.outputs.image-id }}
  tf-plan:
    name: Terraform plan
    strategy:
      fail-fast: false
      matrix:
        env: [dev, prd]
    uses: entur/tmp-github-actions-2/.github/workflows/tf-plan.yml@master
    with:
      tf_version: 1.1.0
      environment: ${{ matrix.env }}
    secrets: inherit

  ci-docker:
    name: CI Docker
    uses: entur/tmp-github-actions-2/.github/workflows/ci-docker.yml@master

  ci-gradle:
    name: CI gradle
    uses: entur/tmp-github-actions-2/.github/workflows/ci-gradle.yml@master
    with:
      app_name: hest-er-best
      java_version: '20'

  ci-insights:
    name: CI insights
    strategy:
      fail-fast: false
      matrix:
        env: [dev, prd]
    uses: entur/tmp-github-actions-2/.github/workflows/ci-insight.yml@master
    with:
      environment: ${{ matrix.env }}
    secrets: inherit


