name: Continous Integration

on:
  pull_request:
    branches:
      - master
      - main
    types:
      - opened
      - synchronize
      - edited

jobs:
  tf-plan:
    permissions:
      contents: 'read'
      id-token: 'write'
    uses: entur/tmp-github-actions-2/.github/workflows/tf-plan.yml@master
    with:
      tf_version: 1.1.0
      environment: dev
    secrets: inherit
  golden-ci:
    uses: entur/tmp-github-actions-2/.github/workflows/golden-ci-rust.yml@master
    # secrets:
    #   token: ${{ secrets.GITHUB_TOKEN }}
